framework:
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/translations'
        paths:
            - '%kernel.project_dir%/templates'
            - '%kernel.project_dir%/src'
        fallbacks:
            - en
        providers:
